### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by lm317379829** [zusterben/plan_b#1]
### 问题描述

helloworld节点采用vless+tcp+xtls模式，xtls流控 选取 xtls-rprx-splice 情况下无法正常使用，原因可能是转化为json配置文件存在问题，转化后的配置文件 flow 的值为空白。helloworld版本为0.2.6。

### 路由型号

AUSU AC-86U

### 固件版本

MerlinR 5.1.3

### 软件中心版本

1.3.1

### 重现步骤

2.helloworld配置 vless+tcp+xtls模式，xtls流控 选取 xtls-rprx-splice无法正常使用。

**Comment by angusguo** [comment]
AX-3000 3.0.0.4.384_TUFAX3000_R5.1.3 
开启v2ray后没有办法上网，并且影响无线使用，具体表现就是无线连不上，关了插件之后正常

**Comment by ilikeboomboomboom** [comment]
科学上网连上出不去

**Comment by ilikeboomboomboom** [comment]
今天更新后能出去了感谢大哥

**Comment by rvpn** [comment]
@lm317379829 

哪里可以下载softcenter 1.3.1版本的ac86u固件？

我的是 1.7.2

![softcenter](https://user-images.githubusercontent.com/28747439/126724929-ee60ede1-9ff5-4fac-9dc7-6a7fafc0bff8.PNG)

**Comment by lm317379829** [comment]
> @lm317379829
> 
> 哪里可以下载softcenter 1.3.1版本的ac86u固件？
> 
> 我的是 1.7.2
> 
> ![softcenter](https://user-images.githubusercontent.com/28747439/126724929-ee60ede1-9ff5-4fac-9dc7-6a7fafc0bff8.PNG)

你用的是Koolshare的固件，去恩山下载，有paldier发布的固件
