### ISSUE TITLE
天邑ty6201a插件安装成功，不能出国

### ISSUE THREAD

**Issue by xfmly** [zusterben/plan_b#14]
机器已改512M，离线安装插件成功，订阅正常，不能出国。

**Comment by shuaigebo** [comment]
同上qq反应也没回

**Comment by xfmly** [comment]
升级5.15b3功能正常，感谢大佬！！！！！

**Comment by shuaigebo** [comment]
昨天我就怀疑是有东西没加进去，现在新版应该解决了。晚上回去试下了，起飞

**Comment by shuaigebo** [comment]
昨天我就怀疑是有东西没加进去，现在新版应该解决了。晚上回去试下了，起飞

**Comment by shuaigebo** [comment]
你用的什么配置，我还是飞不出去
