### ISSUE TITLE
armmg helloworld插件从0.6.9更新至0.7.0后出现“V2Ray配置文件没有通过测试,请检查设置!!!”报错，无法正常使用

### ISSUE THREAD

**Issue by hlj2546** [zusterben/plan_b#35]
反馈bug/问题模板

### (1) 具体问题

A：armmg helloworld插件从0.6.9更新至0.7.0后出现“V2Ray配置文件没有通过测试,请检查设置!!!”报错，无法正常使用；实测，离线回退版本后能正常使用

### (2) 路由器型号

A：rt-ac2200

### (3) 固件版本

A：3.0.0.4.382_RTACRH17_B5.1.7v2-g275f56f

### (4) 软件中心版本

A：1.4.0

### (5) 插件版本

A：0.7.0

### (6) 详细日志

A：
【2022年01月07日 02:42:13】: ======================= 梅林固件 - 【科学上网】 ========================
【2022年01月07日 02:42:13】:
【2022年01月07日 02:42:13】: ------------------------- 启动【科学上网】 -----------------------------
【2022年01月07日 02:42:13】: 插件触发重启定时任务已经删除...
【2022年01月07日 02:42:13】: 删除ss相关的名单配置文件.
【2022年01月07日 02:42:13】: 重启dnsmasq服务...
【2022年01月07日 02:42:15】: 清除iptables规则和ipset...
【2022年01月07日 02:42:16】: 检测到你的v2ray服务器：***不是ip格式！
【2022年01月07日 02:42:16】: 尝试解析v2ray服务器的ip地址，使用DNS：8.8.8.8:53
【2022年01月07日 02:42:17】: 如果此处等待时间较久，建议在【节点域名解析DNS服务器】处更换DNS服务器...
【2022年01月07日 02:42:18】: v2ray***服务器的ip地址解析成功：***
【2022年01月07日 02:42:18】: 创建ipset名单
【2022年01月07日 02:42:20】: 自动判断使用国内优先模式，不加载cdn.conf
【2022年01月07日 02:42:20】: 创建gfwlist的软连接到/etc/dnsmasq.user/文件夹.
【2022年01月07日 02:42:23】: 创建v2ray配置文件到/jffs/softcenter/ss/v2ray.json
【2022年01月07日 02:42:23】: 生成V2Ray配置文件...
【2022年01月07日 02:42:23】: 解析V2Ray配置文件...
【2022年01月07日 02:42:24】: V2Ray配置文件写入成功到/jffs/softcenter/ss/v2ray.json
【2022年01月07日 02:42:24】: 测试V2Ray配置文件.....
【2022年01月07日 02:42:26】: V2Ray配置文件没有通过测试，请检查设置!!!
【2022年01月07日 02:42:26】: 插件将在5秒后自动关闭！！
【2022年01月07日 02:42:27】: 5
【2022年01月07日 02:42:28】: 4
【2022年01月07日 02:42:29】: 3
【2022年01月07日 02:42:30】: 2
【2022年01月07日 02:42:31】: 1
【2022年01月07日 02:42:32】: 0
【2022年01月07日 02:42:35】: 插件已关闭！！
【2022年01月07日 02:42:35】: ======================= 梅林固件 - 【科学上网】 ========================

**Comment by anchengw** [comment]
同样的问题，只不过我的路由器是RTACRH17

**Comment by hlj2546** [comment]
费解，应该不是有些论坛里说的闪存坏块问题

**Comment by xfmly** [comment]
回滚0.68就正常了
