### ISSUE TITLE
Unable to resolve AAAA domain name

### ISSUE THREAD

**Issue by 408029164** [zusterben/plan_b#43]
反馈bug/问题模板

### (1) 具体问题

A：Hi, your project is pretty good. But my rounter fail to connect the vps(IPV6 only), I dont know why, maybe it is a puzzle?
The site “subdomain.domain.com” is deployed on cloudflare, and its DNS resolution type is AAAA.

### (2) 路由器型号

A：EA6700

### (3) 固件版本

A：3.0.0.4.386_EA6700_R5.1.6-g9a49c

### (4) 软件中心版本

A：Software Center EA6700 (base model: RT-AC68U)
软件中心 for arm platform
软件中心：1.4.1

### (5) 插件版本

A：helloworld 0.7.8

### (6) 详细日志

A：
【2022年03月30日 21:16:43】: ======================= 梅林固件 - 【科学上网】 ========================
【2022年03月30日 21:16:43】:
【2022年03月30日 21:16:43】: ------------------------- 启动【科学上网】 -----------------------------
【2022年03月30日 21:16:43】: 关闭xray进程...
【2022年03月30日 21:16:44】: 关闭pdnsd进程...
【2022年03月30日 21:16:44】: 插件触发重启定时任务已经删除...
【2022年03月30日 21:16:44】: 删除ss相关的名单配置文件.
【2022年03月30日 21:16:45】: 重启dnsmasq服务...
【2022年03月30日 21:16:46】: 清除iptables规则和ipset...
【2022年03月30日 21:16:49】: 检测到你的v2ray服务器：【subdomain.domain.com】不是ip格式！
【2022年03月30日 21:16:49】: 尝试解析v2ray服务器的ip地址，使用DNS：8.8.8.8:53
【2022年03月30日 21:16:49】: 如果此处等待时间较久，建议在【节点域名解析DNS服务器】处更换DNS服务器...
【2022年03月30日 21:16:50】: v2ray服务器的ip地址解析失败，将由ss-redir自己解析... 
【2022年03月30日 21:16:51】: 创建ipset名单
【2022年03月30日 21:16:53】: 自动判断dns解析使用国外优先模式...
【2022年03月30日 21:16:53】: 国外解析方案【pdnsd】，需要加载cdn.conf提供国内cdn...
【2022年03月30日 21:16:53】: 生成cdn加速列表到/tmp/sscdn.conf，加速用的dns：114.114.114.114
【2022年03月30日 21:16:56】: 创建cdn加速列表软链接/etc/dnsmasq.user/cdn.conf
【2022年03月30日 21:16:56】: 创建v2ray配置文件到/jffs/softcenter/ss/v2ray.json
【2022年03月30日 21:16:57】: 生成V2Ray配置文件...
【2022年03月30日 21:16:57】: 解析V2Ray配置文件...
【2022年03月30日 21:16:57】: V2Ray配置文件写入成功到/jffs/softcenter/ss/v2ray.json
【2022年03月30日 21:16:57】: 测试V2Ray配置文件.....
【2022年03月30日 21:17:01】: V2Ray配置文件通过测试!!!
【2022年03月30日 21:17:01】: v2ray启动成功，pid：16557
【2022年03月30日 21:17:01】: 开启pdnsd，用于【国外所有网站】的DNS解析...
【2022年03月30日 21:17:02】: 加载nat规则!
【2022年03月30日 21:17:02】: 写入iptables规则到nat表中...
【2022年03月30日 21:17:03】: 加载ACL规则：【全部主机】【全部端口】模式为：大陆白名单模式
【2022年03月30日 21:17:04】: 开启DNS劫持功能功能，防止DNS污染...
【2022年03月30日 21:17:04】: 重启dnsmasq服务...
【2022年03月30日 21:17:05】: ss规则定时更新任务未启用！
【2022年03月30日 21:17:05】: 插件触发重启定时任务已经删除...
【2022年03月30日 21:17:06】: ------------------------ 【科学上网】 启动完毕 ------------------------
【2022年03月30日 21:17:06】:
【2022年03月30日 21:17:06】: Across the Great Wall we can reach every corner in the world!
【2022年03月30日 21:17:06】:
【2022年03月30日 21:17:06】: ======================= 梅林固件 - 【科学上网】 ========================

**Comment by zusterben** [comment]
不支持ipv6
