### ISSUE TITLE
hello world访问控制无法增加自定义接口

### ISSUE THREAD

**Issue by fanghaoji** [zusterben/plan_b#44]
反馈bug/问题模板

### (1) 具体问题

A：hello world访问控制里增加规则，但无法添加自定义接口，目标接口只有三个固定选项

### (2) 路由器型号

A：网件RAX120

### (3) 固件版本

A：3.0.0.4.386_RAX120_R5.1.7v2

### (4) 软件中心版本

A：1.4.3

### (5) 插件版本

A：0.7.8

### (6) 详细日志

A：【2022年03月31日 15:19:50】: ======================= 梅林固件 - 【科学上网】 ========================
【2022年03月31日 15:19:50】:
【2022年03月31日 15:19:50】: ------------------------- 启动【科学上网】 -----------------------------
【2022年03月31日 15:19:50】: 关闭ssr-redir进程...
【2022年03月31日 15:19:50】: 关闭pdnsd进程...
【2022年03月31日 15:19:50】: 关闭dns2socks进程...
【2022年03月31日 15:19:50】: 插件触发重启定时任务已经删除...
【2022年03月31日 15:19:50】: 删除ss相关的名单配置文件.
【2022年03月31日 15:19:50】: 重启dnsmasq服务...
【2022年03月31日 15:19:50】: 清除iptables规则和ipset...
【2022年03月31日 15:19:50】: 删除ss规则定时更新任务...
【2022年03月31日 15:19:51】: 删除SSR定时订阅任务...
【2022年03月31日 15:19:51】: 检测到你的ssr服务器：【jike-jxcn2.jiserver.xyz】不是ip格式！
【2022年03月31日 15:19:51】: 尝试解析ssr服务器的ip地址，使用DNS：8.8.8.8:53
【2022年03月31日 15:19:51】: 如果此处等待时间较久，建议在【节点域名解析DNS服务器】处更换DNS服务器...
【2022年03月31日 15:19:56】: ssr服务器【jike-jxcn2.jiserver.xyz】的ip地址解析成功：120.233.10.49
【2022年03月31日 15:19:56】: 创建ipset名单
【2022年03月31日 15:19:57】: 自动判断dns解析使用国外优先模式...
【2022年03月31日 15:19:57】: 国外解析方案【pdnsd】，需要加载cdn.conf提供国内cdn...
【2022年03月31日 15:19:57】: 生成cdn加速列表到/tmp/sscdn.conf，加速用的dns：119.29.29.29
【2022年03月31日 15:19:58】: 创建cdn加速列表软链接/etc/dnsmasq.user/cdn.conf
【2022年03月31日 15:19:58】: 创建ssr配置文件到/jffs/softcenter/ss/ss.json
【2022年03月31日 15:19:58】: 开启ssr-redir进程，用于透明代理.
【2022年03月31日 15:19:58】: ssr-redir的 tcp 走ssr-redir.
【2022年03月31日 15:19:58】: ssr-redir的 udp 走ssr-redir.
【2022年03月31日 15:19:58】: ssr-redir开启4线程支持.
【2022年03月31日 15:19:58】: ssr-redir -c /jffs/softcenter/ss/ss.json -f /var/run/ss_1.pid
【2022年03月31日 15:19:58】: ssr-redir -c /jffs/softcenter/ss/ss.json -f /var/run/ss_2.pid
【2022年03月31日 15:19:58】: ssr-redir -c /jffs/softcenter/ss/ss.json -f /var/run/ss_3.pid
【2022年03月31日 15:19:58】: ssr-redir -c /jffs/softcenter/ss/ss.json -f /var/run/ss_4.pid
【2022年03月31日 15:19:58】: ssr-redir 启动完毕！.
【2022年03月31日 15:19:58】: 开启pdnsd，用于【国外所有网站】的DNS解析...
【2022年03月31日 15:19:59】: 加载nat规则!
【2022年03月31日 15:19:59】: 写入iptables规则到nat表中...
【2022年03月31日 15:19:59】: 加载TPROXY模块，用于udp转发...
【2022年03月31日 15:19:59】: 加载ACL规则：【全部主机】【全部端口】模式为：大陆白名单模式
【2022年03月31日 15:19:59】: 开启DNS劫持功能功能，防止DNS污染...
【2022年03月31日 15:19:59】: 重启dnsmasq服务...
【2022年03月31日 15:19:59】: 添加ss规则定时更新任务，每天5自动检测更新规则.
【2022年03月31日 15:19:59】: 设置订阅服务器自动更新订阅服务器在星期 6 的 4 点。
【2022年03月31日 15:19:59】: 插件触发重启定时任务已经删除...
【2022年03月31日 15:19:59】: ------------------------ 【科学上网】 启动完毕 ------------------------
【2022年03月31日 15:19:59】:
【2022年03月31日 15:19:59】: Across the Great Wall we can reach every corner in the world!
【2022年03月31日 15:19:59】:
【2022年03月31日 15:19:59】: ======================= 梅林固件 - 【科学上网】 ========================

**Comment by zusterben** [comment]
不支持

**Comment by zusterben** [comment]
更正，添加后，在选框里按说明添加端口

**Comment by fanghaoji** [comment]
![Uploading WX20220331-163527@2x.png…]()
我增加了一个不使用代理的规则，但是目标端口不能修改

**Comment by fanghaoji** [comment]
> 更正，添加后，在选框里按说明添加端口

我增加了一个不使用代理的规则，但是目标端口不能修改
