### ISSUE TITLE
求大佬适配7621AT插件

### ISSUE THREAD

**Issue by zhzmst2020** [zusterben/plan_b#8]
现在7621AT华硕改版固件不只是华硕ac85p了，还有黑猫的极路由4、极路由4増强版、极路由B70、小米r3g、新路由3以及中兴E8820s，请求大佬为这些路由器适配插件吧，让7621AT的生态链搞起来吧，谢谢！

**Comment by zusterben** [comment]
https://github.com/MerlinRdev/Supported_Devices/blob/master/Supported_Devices.md

没出现在这里的自己想办法
